
services:








  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"      
      - "15672:15672"    
    env_file:
      - .env

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped









  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - 9090:9090



networks:
  default:
    name: microservices-network
    external: true