services:
  postgres:
    image: "postgres:12-alpine"
    ports: 
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s




  subscription-service:
    build:
      context: ../../
      dockerfile: services/subscription/Dockerfile
    env_file:
      - .env 
    ports:
      - ${GRPC_PORT:-8082}:${GRPC_PORT:-8082}



    depends_on:
      postgres:
        condition: service_healthy

      
    restart: always
    command: ["/app/main"]


networks:
  default:
    name: microservices-network
    external: true