services:

  gateway:
    build:
      context: ../../
      dockerfile: services/gateway/Dockerfile
    env_file:
      - .env 
    ports:
      - ${SERVER_PORT:-8080}:${SERVER_PORT:-8080}

      
    restart: always
    command: ["/app/main"]


networks:
  default:
    name: microservices-network
    external: true