services:

  gateway:
    build:
      context: ../../
      dockerfile: services/gateway/Dockerfile
    ports:
      - 8080:8080

      
    restart: always
    command: ["/app/main"]


networks:
  default:
    name: microservices-network
    external: true