services:


  email-service:
    build:
      context: ../../
      dockerfile: services/email/Dockerfile


      
    restart: always
    command: ["/app/main"]

networks:
  default:
    name: microservices-network
    external: true