name: tests
on:
  push:
    branches: [main]
  pull_request:


jobs:
  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.head_ref || github.ref}}
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run integration tests for email service
        working-directory: ./services/email
        run: go test ./tests/integration/

      - name: Run integration tests for weather service
        working-directory: ./services/weather
        run: go test ./tests/integration/

      - name: Run integration tests for subscription service
        working-directory: ./services/subscription
        run: go test ./tests/integration/