name: tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [email, weather, subscription]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run tests for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: go test ./tests/integration/